version: "3"

tasks:
  generate:
    desc: generate the test examples
    cmds:
      - go generate ./_examples/basic/ent
      - go generate ./_examples/custompaths/ent

  go:lint:
    desc: runs golangci-lint, the most annoying opinionated linter ever
    cmds:
      - golangci-lint run --config=.golangci.yaml --verbose --fix

  go:test:
    desc: runs and outputs results of created go tests
    cmds:
      - task: tidy
      - go test ./... -v

  go:tidy:
    desc: runs go mod tidy on the backend
    aliases: [tidy]
    cmds:
      - go mod tidy

  go:all:
    aliases: [go]
    desc: runs all go test and lint related tasks
    cmds:
      - task: go:tidy
      - task: go:lint
      - task: go:test
